title: COMP 5270 - HCI*
description: A website for the Human-Computer Interaction class at UMass Lowell.
theme: just-the-docs

source: docs
destination: docs/_site

url: https://uml-hci.github.io/comp5270-s25
baseurl: "/comp5270-s25"

#aux_links: # remove if you don't want this link to appear on your pages
# Template Repository: https://github.com/YOUR-USERNAME/YOUR-SITE-NAME

# Aux links for the upper right navigation
aux_links:
  "COMP5270 on Blackboard":
    - "https://uml.umassonline.net/ultra/courses/_62886_1/cl/outline"

# Makes Aux links open in a new tab. Default is false
aux_links_new_tab: true

mermaid:
  # Version of mermaid library
  # Pick an available version from https://cdn.jsdelivr.net/npm/mermaid/
  version: "10.7.0"
