title: COMP 5720 Spring 2024
description: A website for the Human-Computer Interaction class at UMass Lowell.
theme: just-the-docs

url: https://uml-hci.github.io/comp5720-s24

#aux_links: # remove if you don't want this link to appear on your pages
 # Template Repository: https://github.com/YOUR-USERNAME/YOUR-SITE-NAME
